CREATE TABLE file
(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    desc TEXT,
    path TEXT NOT NULL
);
CREATE UNIQUE INDEX file_path_uindex ON file (path);

CREATE TABLE tag
(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE tag_file
(
    tag INTEGER,
    file INTEGER,
    CONSTRAINT tag_file_tag_file_pk PRIMARY KEY (tag, file),
    FOREIGN KEY (tag) REFERENCES tag (id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (file) REFERENCES file (id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE tag_graph
(
    parent INTEGER,
    child INTEGER,
    CONSTRAINT tag_graph_parent_child_pk PRIMARY KEY (parent, child),
    FOREIGN KEY (parent) REFERENCES tag (id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (child) REFERENCES tag (id) ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED
);